name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PNPM_REGISTRY: https://registry.npmjs.org/

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Enable Corepack + pin pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.15.1 --activate
          pnpm -v
          pnpm config set registry $PNPM_REGISTRY

      - name: Install
        run: |
          pnpm install --no-frozen-lockfile --reporter=append-only

      - name: Build
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
